// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader } from "nanopack"

import { Widget } from "./widget.np.js"
import { Center } from "../center/center.np.js"
import { Text } from "../text/text.np.js"
import { Column } from "../column/column.np.js"

function makeWidget(bytes: Uint8Array) {
	const reader = new NanoBufReader(bytes)
	switch (reader.readTypeId()) {
		case 100:
			return Widget.fromReader(reader)
		case 102:
			return Center.fromReader(reader)
		case 101:
			return Text.fromReader(reader)
		case 103:
			return Column.fromReader(reader)
		default:
			return null
	}
}

export { makeWidget }
