// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter } from "nanopack"

import { Widget } from "../widget/widget.np.js"

class Column extends Widget {
	public static TYPE_ID = 103

	constructor(
		public tag: number | null,
		public children: Widget[],
	) {
		super(tag)
	}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: Column } | null {
		const reader = new NanoBufReader(bytes)
		return Column.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: Column } | null {
		let ptr = 12

		let tag: number | null
		if (reader.readFieldSize(0) >= 0) {
			tag = reader.readInt32(ptr)
			ptr += 4
		} else {
			tag = null
		}

		const childrenLength = reader.readInt32(ptr)
		ptr += 4
		const children: Widget[] = new Array(childrenLength)
		for (let i = 0; i < childrenLength; i++) {
			const maybeIItem = Widget.fromReader(reader.newReaderAt(ptr))
			if (!maybeIItem) {
				return null
			}
			const iItem = maybeIItem.result
			ptr += maybeIItem.bytesRead
			children[i] = iItem
		}

		return { bytesRead: ptr, result: new Column(tag, children) }
	}

	public override get typeId(): number {
		return 103
	}

	public override bytes(): Uint8Array {
		const writer = new NanoBufWriter(12)
		writer.writeTypeId(103)

		if (this.tag) {
			writer.appendInt32(this.tag)
			writer.writeFieldSize(0, 4)
		} else {
			writer.writeFieldSize(0, -1)
		}

		writer.appendInt32(this.children.length)
		let childrenByteLength = 4
		for (const iItem of this.children) {
			const iItemData = iItem.bytes()
			writer.appendBytes(iItemData)
			childrenByteLength += iItemData.byteLength
		}
		writer.writeFieldSize(1, childrenByteLength)

		return writer.bytes
	}

	public override bytesWithLengthPrefix(): Uint8Array {
		const writer = new NanoBufWriter(12 + 4, true)
		writer.writeTypeId(103)

		if (this.tag) {
			writer.appendInt32(this.tag)
			writer.writeFieldSize(0, 4)
		} else {
			writer.writeFieldSize(0, -1)
		}

		writer.appendInt32(this.children.length)
		let childrenByteLength = 4
		for (const iItem of this.children) {
			const iItemData = iItem.bytes()
			writer.appendBytes(iItemData)
			childrenByteLength += iItemData.byteLength
		}
		writer.writeFieldSize(1, childrenByteLength)

		writer.writeLengthPrefix(writer.currentSize - 4)

		return writer.bytes
	}
}

export { Column }
