// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

class OnValueChanged implements NanoPackMessage {
	public static TYPE_ID = 1768749598

	public readonly typeId: number = 1768749598

	public readonly headerSize: number = 8

	constructor(public newValue: string) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: OnValueChanged } | null {
		const reader = new NanoBufReader(bytes)
		return OnValueChanged.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: OnValueChanged } | null {
		let ptr = 8

		const newValueByteLength = reader.readFieldSize(0)
		const newValue = reader.readString(ptr, newValueByteLength)
		ptr += newValueByteLength

		return { bytesRead: ptr, result: new OnValueChanged(newValue) }
	}

	public writeTo(writer: NanoBufWriter, offset: number = 0): number {
		let bytesWritten = 8

		writer.writeTypeId(1768749598, offset)

		const newValueByteLength = writer.appendString(this.newValue)
		writer.writeFieldSize(0, newValueByteLength, offset)
		bytesWritten += newValueByteLength

		return bytesWritten
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(8)
		this.writeTo(writer)
		return writer.bytes
	}
}

export { OnValueChanged }
