// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

import { Widget } from "./widget/widget.np.js"
import { makeWidget } from "./widget/make-widget.np.js"

class CreateWidget implements NanoPackMessage {
	public static TYPE_ID = 20

	constructor(
		public widget: Widget,
		public windowTag: string,
	) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: CreateWidget } | null {
		const reader = new NanoBufReader(bytes)
		return CreateWidget.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: CreateWidget } | null {
		let ptr = 12

		const maybe_widget = makeWidget(reader.slice(ptr))
		if (!maybe_widget) {
			return null
		}
		const widget = maybe_widget.result
		ptr += maybe_widget.bytesRead

		const windowTagByteLength = reader.readFieldSize(1)
		const windowTag = reader.readString(ptr, windowTagByteLength)
		ptr += windowTagByteLength

		return { bytesRead: ptr, result: new CreateWidget(widget, windowTag) }
	}

	public get typeId(): number {
		return 20
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(12)
		writer.writeTypeId(20)

		const widgetData = this.widget.bytes()
		writer.appendBytes(widgetData)
		writer.writeFieldSize(0, widgetData.byteLength)

		const windowTagByteLength = writer.appendString(this.windowTag)
		writer.writeFieldSize(1, windowTagByteLength)

		return writer.bytes
	}

	public bytesWithLengthPrefix(): Uint8Array {
		const writer = new NanoBufWriter(16, true)
		writer.writeTypeId(20)

		const widgetData = this.widget.bytes()
		writer.appendBytes(widgetData)
		writer.writeFieldSize(0, widgetData.byteLength)

		const windowTagByteLength = writer.appendString(this.windowTag)
		writer.writeFieldSize(1, windowTagByteLength)

		writer.writeLengthPrefix(writer.currentSize - 4)

		return writer.bytes
	}
}

export { CreateWidget }
