// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

import { Widget } from "./widget/widget.np.js"

class UpdateWidget implements NanoPackMessage {
	public static TYPE_ID = 1016534798

	public readonly typeId: number = 1016534798

	public readonly headerSize: number = 16

	constructor(
		public tag: number,
		public widget: Widget,
		public args: NanoBufReader | null,
	) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: UpdateWidget } | null {
		const reader = new NanoBufReader(bytes)
		return UpdateWidget.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: UpdateWidget } | null {
		let ptr = 16

		const tag = reader.readInt32(ptr)
		ptr += 4

		const maybeWidget = Widget.fromReader(reader.newReaderAt(ptr))
		if (!maybeWidget) {
			return null
		}
		const widget = maybeWidget.result
		ptr += maybeWidget.bytesRead

		let args: NanoBufReader | null
		if (reader.readFieldSize(2) >= 0) {
			const argsByteLength = reader.readFieldSize(2)
			args = reader.newReaderAt(ptr, ptr + argsByteLength)
			ptr += argsByteLength
		} else {
			args = null
		}

		return { bytesRead: ptr, result: new UpdateWidget(tag, widget, args) }
	}

	public writeTo(writer: NanoBufWriter, offset: number = 0): number {
		const writerSizeBefore = writer.currentSize

		writer.writeTypeId(1016534798, offset)

		writer.appendInt32(this.tag)
		writer.writeFieldSize(0, 4, offset)

		const widgetData = this.widget.bytes()
		writer.appendBytes(widgetData)
		writer.writeFieldSize(1, widgetData.byteLength, offset)

		if (this.args) {
			writer.writeFieldSize(2, this.args.bytes.byteLength, offset)
			writer.appendBytes(this.args.bytes)
		} else {
			writer.writeFieldSize(2, -1, offset)
		}

		return writer.currentSize - writerSizeBefore
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(16)
		this.writeTo(writer)
		return writer.bytes
	}
}

export { UpdateWidget }
