// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

class ListViewOperation implements NanoPackMessage {
	public static TYPE_ID = 3516816492

	public readonly typeId: number = 3516816492

	public readonly headerSize: number = 8

	constructor(public tag: number) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: ListViewOperation } | null {
		const reader = new NanoBufReader(bytes)
		return ListViewOperation.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: ListViewOperation } | null {
		let ptr = 8

		const tag = reader.readInt32(ptr)
		ptr += 4

		return { bytesRead: ptr, result: new ListViewOperation(tag) }
	}

	public writeTo(writer: NanoBufWriter, offset: number = 0): number {
		let bytesWritten = 8

		writer.writeTypeId(3516816492, offset)

		writer.appendInt32(this.tag)
		writer.writeFieldSize(0, 4, offset)
		bytesWritten += 4

		return bytesWritten
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(8)
		this.writeTo(writer)
		return writer.bytes
	}
}

export { ListViewOperation }
