// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

import { Widget } from "../widget/widget.np.js"

class ListViewItem implements NanoPackMessage {
	public static TYPE_ID = 1100735111

	public readonly typeId: number = 1100735111

	public readonly headerSize: number = 12

	constructor(
		public itemTag: number,
		public widget: Widget,
	) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: ListViewItem } | null {
		const reader = new NanoBufReader(bytes)
		return ListViewItem.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: ListViewItem } | null {
		let ptr = 12

		const itemTag = reader.readUint32(ptr)
		ptr += 4

		const maybeWidget = Widget.fromReader(reader.newReaderAt(ptr))
		if (!maybeWidget) {
			return null
		}
		const widget = maybeWidget.result
		ptr += maybeWidget.bytesRead

		return { bytesRead: ptr, result: new ListViewItem(itemTag, widget) }
	}

	public writeTo(writer: NanoBufWriter, offset: number = 0): number {
		const writerSizeBefore = writer.currentSize

		writer.writeTypeId(1100735111, offset)

		writer.appendUint32(this.itemTag)
		writer.writeFieldSize(0, 4, offset)

		const widgetData = this.widget.bytes()
		writer.appendBytes(widgetData)
		writer.writeFieldSize(1, widgetData.byteLength, offset)

		return writer.currentSize - writerSizeBefore
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(12)
		this.writeTo(writer)
		return writer.bytes
	}
}

export { ListViewItem }
