// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter } from "nanopack"

import { ListViewOperation } from "./list-view-operation.np.js"

class ListViewDeleteOperation extends ListViewOperation {
	public static TYPE_ID = 2223513129

	public override readonly typeId: number = 2223513129

	public override readonly headerSize: number = 12

	constructor(
		public tag: number,
		public deleteAt: number[],
	) {
		super(tag)
	}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: ListViewDeleteOperation } | null {
		const reader = new NanoBufReader(bytes)
		return ListViewDeleteOperation.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: ListViewDeleteOperation } | null {
		let ptr = 12

		const tag = reader.readInt32(ptr)
		ptr += 4

		const deleteAtByteLength = reader.readFieldSize(1)
		const deleteAtLength = deleteAtByteLength / 4
		const deleteAt: number[] = new Array(deleteAtLength)
		for (let i = 0; i < deleteAtLength; i++) {
			const iItem = reader.readInt32(ptr)
			ptr += 4
			deleteAt[i] = iItem
		}

		return {
			bytesRead: ptr,
			result: new ListViewDeleteOperation(tag, deleteAt),
		}
	}

	public override writeTo(writer: NanoBufWriter, offset: number = 0): number {
		let bytesWritten = 12

		writer.writeTypeId(2223513129, offset)

		writer.appendInt32(this.tag)
		writer.writeFieldSize(0, 4, offset)
		bytesWritten += 4

		const deleteAtByteLength = this.deleteAt.length * 4
		writer.writeFieldSize(1, deleteAtByteLength, offset)
		for (const deleteAt of this.deleteAt) {
			writer.appendInt32(deleteAt)
		}
		bytesWritten += deleteAtByteLength

		return bytesWritten
	}

	public override bytes(): Uint8Array {
		const writer = new NanoBufWriter(12)
		this.writeTo(writer)
		return writer.bytes
	}
}

export { ListViewDeleteOperation }
