// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

import { Widget } from "../widget/widget.np.js"

class ListViewItem implements NanoPackMessage {
	public static TYPE_ID = 1100735111

	constructor(
		public itemTag: number,
		public widget: Widget,
	) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: ListViewItem } | null {
		const reader = new NanoBufReader(bytes)
		return ListViewItem.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: ListViewItem } | null {
		let ptr = 12

		const itemTag = reader.readUint32(ptr)
		ptr += 4

		const maybeWidget = Widget.fromReader(reader.newReaderAt(ptr))
		if (!maybeWidget) {
			return null
		}
		const widget = maybeWidget.result
		ptr += maybeWidget.bytesRead

		return { bytesRead: ptr, result: new ListViewItem(itemTag, widget) }
	}

	public get typeId(): number {
		return 1100735111
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(12)
		writer.writeTypeId(1100735111)

		writer.appendUint32(this.itemTag)
		writer.writeFieldSize(0, 4)

		const widgetData = this.widget.bytes()
		writer.appendBytes(widgetData)
		writer.writeFieldSize(1, widgetData.byteLength)

		return writer.bytes
	}

	public bytesWithLengthPrefix(): Uint8Array {
		const writer = new NanoBufWriter(12 + 4, true)
		writer.writeTypeId(1100735111)

		writer.appendUint32(this.itemTag)
		writer.writeFieldSize(0, 4)

		const widgetData = this.widget.bytes()
		writer.appendBytes(widgetData)
		writer.writeFieldSize(1, widgetData.byteLength)

		writer.writeLengthPrefix(writer.currentSize - 4)

		return writer.bytes
	}
}

export { ListViewItem }
