// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader } from "nanopack"

import { ListViewOperation } from "./list-view-operation.np.js"
import { ListViewInsertOperation } from "./list-view-insert-operation.np.js"
import { ListViewDeleteOperation } from "./list-view-delete-operation.np.js"

function makeListViewOperation(bytes: Uint8Array) {
	const reader = new NanoBufReader(bytes)
	switch (reader.readTypeId()) {
		case 3516816492:
			return ListViewOperation.fromReader(reader)
		case 2077451345:
			return ListViewInsertOperation.fromReader(reader)
		case 2223513129:
			return ListViewDeleteOperation.fromReader(reader)
		default:
			return null
	}
}

export { makeListViewOperation }
